package com.bjpowernode.p2p.mapper.loan;

import com.bjpowernode.p2p.model.loan.BidInfo;

import java.util.List;
import java.util.Map;

public interface BidInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    int insert(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    int insertSelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    BidInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    int updateByPrimaryKeySelective(BidInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_bid_info
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    int updateByPrimaryKey(BidInfo record);


    /**
     *
     * 查询累计金额
     * @return
     */
    Double selectAllBidMoney();

    /**
     * 根据产品标识获取产品详情
     * @param id
     * @return
     */
    List<BidInfo> selectBidInfoListByLoanId(Integer id);

    /**
     * 查询投资记录
     * @param paramMap
     * @return
     */
    List<BidInfo> selectBidInfoByPage(Map<String, Object> paramMap);

    /**
     * 据用户标识分页查询所有投资列表
     * @param paramMap
     * @return
     */
    Long selectTotal(Map<String, Object> paramMap);

    /**
     * 根据产品标识获取产品的所有投资记录
     * @param id
     * @return
     */
    List<BidInfo> selectBidInfosLoanId(Integer id);
}