package com.bjpowernode.p2p.model.user;

import java.io.Serializable;
//用户财务资金账户表
public class FinanceAccount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_finance_account.id
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    //用户财务资金账户标识
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_finance_account.uid
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    //用户标识
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_finance_account.available_money
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    //用户可用资金
    private Double availableMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_finance_account.id
     *
     * @return the value of u_finance_account.id
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_finance_account.id
     *
     * @param id the value for u_finance_account.id
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_finance_account.uid
     *
     * @return the value of u_finance_account.uid
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_finance_account.uid
     *
     * @param uid the value for u_finance_account.uid
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_finance_account.available_money
     *
     * @return the value of u_finance_account.available_money
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    public Double getAvailableMoney() {
        return availableMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_finance_account.available_money
     *
     * @param availableMoney the value for u_finance_account.available_money
     *
     * @mbggenerated Mon Mar 25 19:31:18 CST 2019
     */
    public void setAvailableMoney(Double availableMoney) {
        this.availableMoney = availableMoney;
    }
}